### ISSUE TITLE
No Message Persistence

### ISSUE THREAD

**Issue by bacloud22** [bacloud22/Highest-priest-GPT#1]
Issue: Currently, messages are ephemeral. Users cannot retrieve past questions/answers if they reload the page or lose connection.

Improvement: Add message persistence (either using PubNub’s storage feature or native local storage a local DB like **PouchDB**) so users can see previous conversations when they reconnect.

**Comment by moo-light** [comment]
hey i want to try this issue it seem really cool.
 
i also want to add a way for questioner to join the chat before establish a connection but i don't have a good text to add to the button yet. Any suggestion?
![image](https://github.com/user-attachments/assets/ab3167d5-8d94-4779-8b9d-2115596b32c0)

**Comment by bacloud23** [comment]
I don't understand you at all.

**Comment by moo-light** [comment]
> Issue: Currently, messages are ephemeral. Users cannot retrieve past questions/answers if they reload the page or lose connection.
> 
> Improvement: Add message persistence (either using PubNub’s storage feature or native local storage a local DB like **PouchDB**) so users can see previous conversations when they reconnect.

okay i like this issue you're given 

i also have another idea to have people who joined the channel to have a username displayed on the chat log
![image](https://github.com/user-attachments/assets/6946b471-fd9f-4341-bcc4-8b476666f10c)

but if i want to do that i need to implement user join channel action
![image](https://github.com/user-attachments/assets/b6a31829-8235-4157-9602-9ef85f3ed92b)
but currently i don't know what text should i added to the button so i put it as `joinChannel_text`

**Comment by bacloud23** [comment]
Please don't. Because a user joining a channel event is already logged. Plus, if you talking about the questioner role not displaying logs, it means you didn't understand what this app is about.

**Comment by moo-light** [comment]
okay thank you for pulling me back before i messed up 

i would like to try improve the message persistent.

**Comment by bacloud23** [comment]
How would you do it?

**Comment by moo-light** [comment]
I going to try to do it but saving it to localstorage everytime mesage log updated
Then when user load the chanel with the id it will check the id and append the message log only once
If the user switch to a different language it will switch to that language too

**Comment by bacloud23** [comment]
very nice ! let's go.

**Comment by bacloud23** [comment]
still on it?

**Comment by bacloud23** [comment]
Last check before unassign

**Comment by moo-light** [comment]
yes i'm still on it kinda busy irl

**Comment by bacloud23** [comment]
No worries

**Comment by moo-light** [comment]
yeah i guess this will be a big update
